---
title: "興味"
output: html_document
---

<div style="margin-bottom:60px;">
</div>

# 種間交雑

<div style="margin-bottom:30px;">
</div>

## F1雑種オスのモテ形質の一般的特徴（進行中）

<div style="margin-bottom:30px;">
</div>

種間交雑のインパクトを理解するうえで、雑種が誰と交配しやすいかを知ることはとても大事です。しかし雑種の交配パターンは驚くほど調べられていません。そこで、オスがどのようなメスにモテるかに直結する、モテ形質に注目しました。動物全般の交雑研究のデータをまとめて分析し（メタ解析）、雑種のモテ形質はどの親に似るのか、形質の多様性は親種の遺伝的な分化とともにどう変わるのか調べています（Atsumi, Lagisz, Nakagawa *Evolution* 受理）。

<div style="margin-bottom:30px;">
</div>

## 大胆な個体ほど交雑しやすい！？淡水魚ウグイ類を題材に

<div style="margin-bottom:30px;">
</div>

メス装飾のはたらきを調べた下記の研究では、オスの同種メスへの好みの強さが個体によって大きく違っていました。この「種認識能力」が普段の行動と関連しないか調べてみました。新しい水槽の隠れ家にオスを入れ、隠れ家から出てくるまでの時間を調べると、種認識能力が低いオスほどすぐ隠れ家から出てくる「探索的/大胆」な個体であることがわかりました。もしも普段の生活で「探索的/大胆」な個体が有利なら、たとえ交雑自体が損であっても、性格ー交雑の相関を通して交雑が起こり続けてしまうのかもしれません (Atsumi & Koizumi *Journal of Ethology*)。

<div style="margin-bottom:30px;">
</div>

## メスの装飾は交雑回避にも有益｜淡水魚ウグイ類を題材に

<div style="margin-bottom:30px;">
</div>

メスにはたらく性淘汰・社会淘汰での産物、あるいは単なる派手オス進化の副産物として説明されてきました。しかし、メス・オスともに繁殖期に鮮やかな婚姻色を出す魚・ウグイ類でお見合い実験をしたところ、オスは見た目を基にして同種メスを他種メスよりも好むことがわかりました。これは、メスの派手な形質は、他種オスからの求婚を減らす役割もあることを示唆します (Atsumi et al. 2019 *Journal of Ethology* [紹介](https://buna.info/article/2242/))。

ウェブ上のウグイ婚姻色の写真を分析すると、ウグイの婚姻色パターンは他種と共存する地域よりも単独で分布する地域で多様化しています。交雑回避のために種をアピールする必要がなくないことが、単独分布域での多様化を許しているのかもしれません（Atsumi & Koizumi 2017 *Ecological Research* [紹介](https://academist-cf.com/journal/?p=4492)）


よさこい生態学セミナーでお話した内容を
小野遥さん（北大･理 高木研卒業）が可愛くわかりやすくまとめてくれました！

<div style="margin-bottom:60px;">
</div>

# 種内多様性

<div style="margin-bottom:30px;">
</div>

## 可塑性の遺伝的変異が種間関係を決める

</div>

エゾサンショウウオvsエゾアカガエルの幼生同士の食うー食われる関係が、両者の可塑的攻撃・防御の遺伝的な地域変異で決まることを明らかにしました。(Atsumi, Ross & Kishida, Under review)

</div>

## 餌が天敵同士の共食いを誘発する!？

</div>

エゾサンショウウオとキタサンショウウオの幼生を一緒に飼ってみました。キタはエゾよりはるかに小さいので、エゾはキタを食べてみんな仲良く良く育つのだろうと思っていたら、キタを入れた水槽でだけエゾは共食いを始めました（キタは全滅）。もしかすると、キタを食べれたエゾと食べれなかったエゾがいて、その格差が共食いを誘発したのかもしれません。(Atsumi & Kishida *Ecological Research*)

</div>

## 種内多様性が種内多様性を再構築する：齢構造での実験（失敗）

</div>

エゾサンショウウオの幼生には、1年のうちに池から出ていくものと、越冬して翌年も池に残る留年組がいます。彼らの間の食う―食われる関係から、留年組がいると翌年も留年組が現れやすくなると考えて実験したのですが、失敗。でもエゾサンショウウオーエゾアカガエル研究の中で一番好きなテーマだったので、ここで供養をば。苫小牧研究林・天塩研究林での実験。

