---
title: "海外渡航のあれこれ"
output: html_document
---

海外渡航で、特にビザ関連でめんどくさかったことなど、シェアします。一人でも多くの人がスムーズに海外で武者修行できますように。

<div style="margin-bottom:60px;">
</div>

# 海外学振でアメリカJ1ビザをとる｜2020年Texas A&M大学版

<div style="margin-bottom:30px;">
</div>

海外学振合格、おめでとうございます。4月に派遣開始をご希望であれば、時間はありません。**海外学振採用の証明が来たら速やかにスキャンして受け入れ先ボスに連絡**しましょう。

テキサスA&M大学（TAMU）の場合は、5VSという書類への記入から手続きは開始。5VSがFacultyで受理されると、それが外国人受け入れをつかさどるISFSに5VSが渡ります。

このISFSが大学での受け入れの可否を決め、OKであればDS2019という書類がもらえます。DS2019はビザ取得での必要書類で、国土安全保障省への情報登録であるDS160とともに大使館の面接予約に必要です。DS2019には多くの必要書類があります（後述）。

DS2019が取れる見込みが立ったら、国土安全保障省への情報登録であるDS160記入を始めましょう。すごい根掘り葉掘り聞いてくるので時間がかかります。DS160登録完了には、SEVIS料金を払わねばなりません。このSEVIS支払いにはDS2019に記入されるSEVIS IDが必要です。さて、DS160の有効期限は約1か月です。なので、DS160の有効期限内にDS2019が届かないと、SEVISを払えないためにDS160登録が完了せず、せっかく時間をかけて書いたDS160が無駄になります。DS160登録が終わると、いよいよビザ面接です。ここでもお金がかかります（この強欲め）。

ビザ面接がつつがなく終わると、1~3週間でビザが届きます。


曲者なのはDS2019申請に必要な書類たち。

- Curriculum Vitae/Resume

- 学位証明あるいは卒業見込証明書

- 滞在時の研究目的（簡単で良い、5VSに書いたものを転用した）

- Passport

- Proof & Certification of Insurance (translated to English)

- Proof of English language proficiency： ≧80のTOEFL iBT (550 paper-based) か、≧6.0のIELTS. GRE or GMAT verbal scoresあるいは、英語インタビューを受ける（$75かかった）

- Proof of financial support（海外学振採用証明）

- J2ビザで連れていく人たちのDS-2019申請ーパスポート等とともに  

- J-1 Operational Fee - $350(nonrefundable) この強欲め。


保険の加入と、英語能力の証明が必要なのです。


保険には大学が求める様々な条件がありそれを満たす保険に入る必要があります。いろんな方に聞くと、保険はJALやANAが提携する海外旅行保険が良いらしいです。僕は、[JALが提携しているAIGの海外赴任者総合保障制度](https://www.global-protection.co.jp/support1.php)のオプションプランに入りました。滞在先機関と海外学振である旨を伝えればそれにあったプランを提供してくれます。保険は年額約30万円しますが日本語オペレーターに対応をお願いできるようで、その安心料です。


ポスドクで行く人間がなんで英語能力証明しないかんのだ。私は時間がなかったのでいつでも受けられる英語面接にしましたが、そんなのに$75払うなら前もってTOEFLとか受けとけばよかったとすごく後悔しました。



さて、逆算しましょう。

1. 1~3週間ビザが届くまでにかかるという事は、渡航の1か月前にはビザ面接をしたいですよね。

2. 面接予約は1か月弱先まで取れないことがあります。私は2月12日にDS160を登録しましたが、予約が取れたのは3月3日でした。ということは、DS2019が渡航2か月前に欲しいですね。

3. DS160登録にはDS2019が必要ですが、必要書類を揃えて申請してから貰えるまでにも時間がかかります。

ということは**保険や英語証明などの必要書類を2.5か月前には揃えておきたい**。因みにAIGの海外赴任者総合保障制度はJALカードで支払わねばならないので、必要に応じてクレジットカードを作っておく必要があります。

こんな感じで、ビザ取得にはすごく時間がかかります。

ですので、海外学振合格通知をもらったら速やかに準備を始めましょう。

**私の失敗は、手続きの全体を把握していなかったこと、ボスを通じて事務を急かさなかったこと**でした。実は5VSがFacultyに受理されてから、DS2019の必要書類を知らされるまでに約20日間の間がありました。事務に尋ねたものの、その返答が遅かったのです。要するにTAMUの事務は大変お粗末です。

それをようやく学習して、必要書類リストを送られてからは、事務を急かすメールをCCにボスを入れて数日に一回送りつけるようにしました。その結果、あとの手続きは結構早く進みました。

お金もかかりますね、大学やらSEVISやら面接やら...そして保険。しかも面接が遅れたせいで東京まで出向く羽目に。計40万円くらい。しかも向こうに行ったら車も買わないと...。次は海外で雇われるポスドクになりたい。大学やら保険やらは、向こうで雇われる際には免除されているはずです。というわけでポスドクでアメリカを目指す皆さん、海外学振で行く際にはとっってもお金がかかるという事にご留意ください。

<div style="margin-bottom:60px;">
</div>

## コロナ禍でのアメリカ入国｜2021年2月版

<div style="margin-bottom:30px;">
</div>

結論から言います。案外ザルです。[ANA提携のオンライン検査](https://www.ana.co.jp/ja/jp/topics/coronavirus-travel-information/pcr/)で行けました。

ただし、これで**入国/出国に失敗しても責任はとりません**。殆ど情報のない、コロナ禍でのアメリカ入国の情報を提供することが目的で、いかなるキックバックは得ていません。

これは2月、東京→ヒューストン直行便でのお話です。当時のアメリカ入国には、出国72時間以内での検体を基にしたコロナ検査で陰性であることを、出国の飛行機搭乗時に確かめる必要がありました。

そこで問題になるのは、どこでどんな検査を受けるか？です。

「アメリカ入国　コロナ検査　陰性証明書」なんて調べると、検査に3万円、陰性証明書作成に1万円なんてゆうボッタクリクリニックだらけ。検査3万円は10000歩譲ってまあ許すとして、、、書類に1万ってあほか？いやもしかすると、かの隣国がやってるみたいに提携してる医療機関の証明書しかアメリカは受け付けないのか？と逆に疑心暗鬼になるも、アメリカの[CDCサイト](https://www.cdc.gov/quarantine/masks/mask-travel-guidance.html)に特にそのような記述はありません。

これを信じ、安価にできる[オンラインでの検体採取＋検体郵送を組み合わせたサービス](https://www.ana.co.jp/ja/jp/topics/coronavirus-travel-information/pcr/)を使いました。これなら陰性証明書込みで1万円強です。高いですが、4万円ぼられるよりマシ。

後で気づきましたが**最も頼りになるサイトは経産省の[TeCOT](https://www.meti.go.jp/policy/investment/tecot/top.html)**でした。各国の基準を満たす医療機関の一覧が見れ、さらにそこから検査の予約もできます。有能。とはいえ、結局1万円台前半が最安値水準なので、オンラインにした判断は正しかったです。

オンライン検体採取にせよ、TeCOT上の対面検体採取にせよ、**かなり検査の予約は埋まっています**。飛行機を予約したらすぐに検査も予約してしまいましょう。

検体採取は詳細を省きます。安全のため私は、速達＋簡易書留で送りました。検体が朝に検査機関に着いたため、15時ごろには陰性証明書をEメールでもらえました。

**陰性証明書はオフラインでも見れるよう必ずDLしましょう**。到着先の空港では、入国審査までの間はWiFiは飛んでいないからです。印刷の必要はありませんでした。

陰性証明書は飛行機の搭乗チェックイン時に見せましたが、入国審査の時に見せたかは覚えていません。あっけなく入国出来て、嬉しびっくりでした。

以上。お役に立てれば幸いです。


<div style="margin-bottom:60px;">
</div>

# アメリカからメキシコに陸路で行ってそのまま帰る | 出国証明トラブル

<div style="margin-bottom:30px;">
</div>

失敗談です。

アメリカ観光ESTAを使い、テキサスA&M大学に下見に来た時。彼らの調査に同行してメキシコの調査地に陸路で向かい、そのままメキシコシティから日本に帰ってきたときの話です。

Laredoでメキシコに陸路入国するとき、私の頭の中は入国でいっぱいで、アメリカを出国している、ということを忘れていました。もちろん、出国には手続きが必要です...。

日本国籍保持者は基本的に、いろんなアメリカ入国関係の手続きが自動化されています。入国証明書I94がその一つ。I94は、日本人短期滞在者で、空路で入国・帰国する場合には、完全に自動化されているので存在に気付かないでしょう。

これが陸路だと問題になります。メキシコ入国手続きだけ済ませても、アメリカ出国手続き（I94を印刷して、返却）しないと、アメリカを出国したことにならないのです。
詳細はこちら：https://japan2.usembassy.gov/pdfs/wwwf-cbp-i94autoj-faq.pdf

これを忘れると、アメリカから帰ってしばらくしたころに、「君のアメリカ滞在許可期間そろそろ終わるよ」ってゆう恐ろしいメールがやってきます。ここでやらなければならないことは、アメリカのColeman Data Solutionsという期間に、I94を紙で郵送することです（理由書も添えました）。もちろん、国際郵便なので結構お金かかります。

賢明なみなさまがこのようなやらかしをしませんように。