---
title: "完全無料で文献を管理する"
output: html_document
---

<div style="margin-bottom:60px;">
</div>

ここでは、1円も使わずに、

1. 読みたい大量の論文をクラウドする

1. それらの論文を引用文献に自動で加えられるよう管理ソフトに読み込ませる

1. それらの論文を、自分が見つけやすいようにフォルダではなくラベルで管理する

ことを目標にします。

<div style="margin-bottom:60px;">
</div>

# 読みたい大量の論文をクラウドする

<div style="margin-bottom:30px;">
</div>

15GBまで無料の[MEGA](https://ja.wikipedia.org/wiki/MEGA)が便利です。私が導入した2015年頃は50GB無料だったんですが、、、

論文を入れるフォルダを決めて、MEGAにそれを読み込ませればOKです。

<div style="margin-bottom:60px;">
</div>

# 文献管理ソフト

<div style="margin-bottom:30px;">
</div>

私はMendeleyを使っています。クラウドソフトに読み込ませているフォルダをMendeleyに読み込ませるだけでOKです。

Natureによる[文献管理ソフト8選 2017](https://www.natureasia.com/ja-jp/ndigest/v14/n11/TOOLBOX%3A+%E6%96%87%E7%8C%AE%E7%AE%A1%E7%90%86%E3%82%BD%E3%83%95%E3%83%888%E9%81%B8/89727)を見るとMendeley・Zotero・colwizの3強でしょうか。Readcubeは2016年頃まで使っていましたが、使い勝手が悪く撤退しました。残念なことにZotero・Colwizは使ったことがありません。

Mendeley無料版でも、

- Word pluginで、ほぼすべての雑誌フォーマットで引用文献リストを作ってくれる（ちなみにフォーマットは自分で作れます、申請書用と日本生態学会誌用は自作しました）

- もう読む気もないけど引用文献に入れるかもしれない文献の情報を、ファイルがなくとも残しておける（実ファイルはPCのフォルダから消してOK、容量節約）
ことができます。十分ですよね。

論文をMendeley上で読んでそこにメモをつけたりして、それを複数端末で共有しようとすると、有料オプションを使うことになります。でも、あくまで論文を読む・メモをつけるのをAcrobat readerにしておけば、クラウド上で編集内容はすべて同期できるから、有料オプションを使う必要はありません。

Zoteroはオープンソースである分、Rのようにかなりの発展を遂げるのではないかと期待しています。例えば、Libreoffice対応のPluginがあるのは素晴らしいですね。これでMS officeを使わずに論文が書ける（そもそもTexとRmarkdownを組み合わせて使えばいいのですが）。いつかはZoteroかColwizに移る時が来るのでしょう...。

<div style="margin-bottom:60px;">
</div>

# 論文を、自分が見つけやすいようにフォルダではなくラベルで管理する

<div style="margin-bottom:30px;">
</div>

論文って分野だったり手法だったり色んな属性がありますよね。分野も複数にまたがってたり。その属性ごとにファイルを管理しようと思うと、フォルダでやろうとするとどうしても無理が出てきます。やたらとフォルダが増えるとか。

これを解決するのが、知る人ぞ知る超便利ファイル管理ソフト、[Fenrir FS](https://www.fenrir-inc.com/jp/fenrirfs/)。

Fenrir FSにフォルダを読み込ませると（ここではクラウド・文献管理ソフトの読み込み対象になっているフォルダ群）、ファイルに対しまず所属フォルダ名と同じ**ラベル**が付きます。ここで重要なのは、Fenrir FS上でラベルを好きなだけ追加できることです。ラベル一覧上で気になるラベルをクリックすると、そのラベルがついたすべてのファイルを閲覧できます。検索窓でワード検索すると、ファイル名・ラベル名が検索対象になって一覧が出てきます。

ただし、各ファイルに着けたラベルは複数端末では共有できません。

公式サイトを見るのが早いです。

最後に、**自分が論文を探すときのことを考えて、ファイル名は機能的に**しましょう。つまり検索に使いそうなキーワードは全てラベルかファイル名に含めておくべきです。Atsumi et al. 2021なんて最悪です。だってそれを見たところで絶対中身わかんない/思い出せないですから。

例えば自分は、

- {ラベルでカバーしないTopic名}\_{論文のタイプ：Review, Metaanalysis, Mathmodel, 他は無し}\_{year}\_{簡単な内容}\_{筆頭著者（+自分が気にしてる著者）}\_{雑誌名} 

としています。
